spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springreactdemo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: springreactdemo
server:
  port: 8081
security:
  basic:
    enabled: false
  ignored: /**
